apiVersion: batch/v1
kind: Job
metadata:
  labels:
    jobgroup: linformer-job
  name: zihan-vanilla-linformer
spec:
  parallelism: 3
  backoffLimit: 3
  template:
    spec:
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command:
        - /bin/sh
        - -c
        args:
        - |
          git clone --single-branch --branch master https://github.com/JavierZhao/linformer4HEP.git /opt/repo/linformer4HEP && \
          chown -R 1000:1000 /opt/repo/linformer4HEP
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
      containers:
      - name: testing
        image: gitlab-registry.nrp-nautilus.io/jmduarte/hbb_interaction_network:latest
        command:
        - /bin/bash
        args:
        - -c
        - |
          cd /opt/repo/linformer4HEP/scripts &&
          ./run_all.sh \
          --data_dir /j-jepa-vol/l1-jet-id/data/jetid/processed \
          --save_dir /j-jepa-vol/linformer4HEP/runs/double_batch_size/vanilla \
          --batch_size 4096 \
          --num_epochs 1000 \
          --d_model 16 --d_ff 16 --num_heads 4 --proj_dim 4 \
          --num_particles      16,32,150 \
          --sort_by            pt,delta_R,kt
        resources:
          limits:
            cpu: '4'
            memory: 26Gi
            nvidia.com/gpu: 1
          requests:
            cpu: '4'
            memory: 22Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: j-jepa-vol
          mountPath: /j-jepa-vol
        ports:
        - containerPort: 6006  # Expose the TensorBoard port
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: j-jepa-vol
        persistentVolumeClaim:
          claimName: j-jepa-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - gpn-fiona-mizzou-2.rnet.missouri.edu
                  - rci-nrp-gpu-05.sdsu.edu
                  - node-2-2.sdsc.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080-Ti
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    jobgroup: linformer-job
  name: zihan-vanilla-linformer-share-ef
spec:
  parallelism: 3
  backoffLimit: 3
  template:
    spec:
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command:
        - /bin/sh
        - -c
        args:
        - |
          git clone --single-branch --branch master https://github.com/JavierZhao/linformer4HEP.git /opt/repo/linformer4HEP && \
          chown -R 1000:1000 /opt/repo/linformer4HEP
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
      containers:
      - name: testing
        image: gitlab-registry.nrp-nautilus.io/jmduarte/hbb_interaction_network:latest
        command:
        - /bin/bash
        args:
        - -c
        - |
          cd /opt/repo/linformer4HEP/scripts &&
          ./run_all.sh \
          --data_dir /j-jepa-vol/l1-jet-id/data/jetid/processed \
          --save_dir /j-jepa-vol/linformer4HEP/runs/double_batch_size/conv/share-ef \
          --cluster_E --cluster_F \
          --share_EF \
          --convolution \
          --batch_size 4096 \
          --num_epochs 1000 \
          --d_model 16 --d_ff 16 --num_heads 4 --proj_dim 4 \
          --num_particles      16,32,150 \
          --sort_by            pt,delta_R,kt
        resources:
          limits:
            cpu: '4'
            memory: 26Gi
            nvidia.com/gpu: 1
          requests:
            cpu: '4'
            memory: 22Gi
            nvidia.com/gpu: 1
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: j-jepa-vol
          mountPath: /j-jepa-vol
        ports:
        - containerPort: 6006  # Expose the TensorBoard port
      volumes:
      - name: git-repo
        emptyDir: {}
      - name: j-jepa-vol
        persistentVolumeClaim:
          claimName: j-jepa-vol
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - gpn-fiona-mizzou-2.rnet.missouri.edu
                  - rci-nrp-gpu-05.sdsu.edu
                  - node-2-2.sdsc.optiputer.net
              - key: nvidia.com/gpu.product
                operator: In
                values:
                - NVIDIA-GeForce-GTX-1080-Ti